Repository JoaquinDeLuca/mytinerary-back-deluca-ochoa-ojeda, pull requests merged in 2022-08, with the labels that each got.

#5 B3-mongo
  .env.example
  app.js
  bin/www
  config/database.js
  package-lock.json
  package.json
Labels: database

#17 B5-mytinerary
  controllers/cityController.js
  routes/cities.js
  routes/index.js
Labels: Endpoint

#21 Issue cors
  app.js
  package-lock.json
  package.json
Labels: component

#22 issue-cors
  app.js
Labels: component
